server:
  port: 1006
spring:
  application:
    #  需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
    name: baas-config
#  指定主机名称
#  cloud:
#    client.hostname: localhost


# 在配置文件中注明自己的服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
# 开启除了主机名也可以通过ip来定义注册中心地址
  instance:
    prefer-ip-address: true
    ip-address: localhost
    # 定义服务续约任务的调用间隔时间，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 定义服务失效的时间，默认为90秒
    lease-expiration-duration-in-seconds: 90
#    preferIpAddress: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}





# 配置config中心
spring.cloud.config:
  server:
#  配置git仓库地址 http方式
#    git.uri: https://github.com/zhangboqing/zbq-config-center.git
#  配置git仓库地址 ssh方式
    git:
     uri: ssh://git@github.com:18689857620/new.git
#  跳过ssh校验
#      skipSslValidation: true
     ignoreLocalSshSettings: true
     username: 18689857620
     password: 1466004117@qq.com
#  下面两个参数没怎么弄明白，配上不好用，感兴趣的可以研究下
#      hostKey: someHostKey
#      hostKeyAlgorithm: ssh-rsa
#     privateKey:  |
#                    -----BEGIN RSA PRIVATE KEY-----
#                    你的私钥
#                    -----END RSA PRIVATE KEY-----
##  配置仓库路径下相对搜索位置，可以配置多个
#     searchPaths: zbq/myconfig1,zbq/myconfig2
# 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
#  访问git仓库的用户名
#    username:
#  访问git仓库的用户密码
#    password:
# 配置仓库的分支
  label: master
#logging:
logging:
  level:
    root: info
    additivity: off
  file: /data/home/logs/zbq-config-server/zbq-config-server.log